spring:
  application:
    name: Testes
  datasource:
    url: jdbc:postgresql://testes-db:5432/testes
    username: postgres
    password: ${PG_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
server:
  port: 8080