services:

  # Database da API Apollo
  testes-db:
    image: postgres:17.2-alpine3.21
    container_name: testes-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testes
    ports:
      - "9432:5432"
    networks:
      - testes
    mem_limit: 128m # Limite máximo de memória
    cpus: 1 # Limite máximo de cpu
  
  # API Apollo
  testes:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: testes/testes:1.0
    pull_policy: never
    container_name: testes
    ports:
      - "9081:8080"
      - "6006:5005" # Porta de depuração remota
    depends_on:
      - testes-db
    volumes:
      - ..:/app
    networks:
      - testes
    mem_limit: 4G # Limite máximo de memória
    cpus: 4 # Limite máximo de cpu
  
networks:
  testes:
    external: true
    driver: bridge
